/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ssinghal' at '1/24/15 7:48 PM' with Gradle 2.2
 *
 * @author ssinghal, @date 1/24/15 7:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
